### ISSUE TITLE
IndexError in mass spec

### ISSUE THREAD

**Issue by joewandy** [sdrogers/vimms#258]
1. Got this error:
```
/opt/anaconda3/envs/vimms/bin/python /Users/joewandy/Work/git/vimms/vimms/scripts/debug_ross.py 
2023-03-14 15:47:32.716 | DEBUG    | vimms.ChemicalSamplers:sample:84 - 73822 unique formulas in filtered database
2023-03-14 15:47:32.719 | DEBUG    | vimms.ChemicalSamplers:sample:90 - Sampled formulas
2023-03-14 15:47:32.741 | DEBUG    | vimms.Chemicals:sample:664 - Sampled rt and intensity values and chromatograms
2023-03-14 15:47:32.768 | DEBUG    | vimms.Chemicals:__init__:477 - FastMemoryChems initialised
(5.200s) ms_level=1:   0%|          | 5.2/1440 [00:00<00:01, 958.87it/s] 
Traceback (most recent call last):
  File "/Users/joewandy/Work/git/vimms/vimms/scripts/debug_ross.py", line 32, in <module>
    env.run()
  File "/Users/joewandy/Work/git/vimms/vimms/Environment.py", line 87, in run
    raise e
  File "/Users/joewandy/Work/git/vimms/vimms/Environment.py", line 83, in run
    scan = self._one_step()
  File "/Users/joewandy/Work/git/vimms/vimms/Environment.py", line 110, in _one_step
    scan = self.mass_spec.step(params=params)
  File "/Users/joewandy/Work/git/vimms/vimms/MassSpec.py", line 398, in step
    new_scan = self._get_scan(self.time, params)
  File "/Users/joewandy/Work/git/vimms/vimms/MassSpec.py", line 611, in _get_scan
    chems, chemical_peaks = self._get_chem_peaks(isolation_windows, scan_time,
  File "/Users/joewandy/Work/git/vimms/vimms/MassSpec.py", line 674, in _get_chem_peaks
    chemical_peaks = self._get_chem_peaks_for_ms2(chems, self.chem_data_collector,
  File "/Users/joewandy/Work/git/vimms/vimms/MassSpec.py", line 692, in _get_chem_peaks_for_ms2
    self._isolate_chems_for_fragmentation(
  File "/Users/joewandy/Work/git/vimms/vimms/MassSpec.py", line 719, in _isolate_chems_for_fragmentation
    isolated_chems = chems[isolated]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 1 but corresponding boolean dimension is 4

Process finished with exit code 1
```

2. Shouldn't this be caught by the unit tests? But they all pass (locally). Maybe related to #254

**Comment by joewandy** [comment]
@mcbrider5002 I just pushed the fixes to the main branch. Could you give it a test please? 

The error was because my codes didn't handle chemicals having multiple isotopes & adducts, which were the case for those HMDB chemicals. During development, I only tested with chems having 1 isotope (monoisotope) and adduct (M+H).

Some observations while debugging:

1. The frag events look exactly the same before and after the speed-up changes .. so that's good. Here's an example with 2 chemicals.

**BEFORE**

<img width="1169" alt="Screenshot 2023-03-30 at 17 14 28" src="https://user-images.githubusercontent.com/2523391/228902505-7b085d9c-2c36-4a12-aa13-06cd8877b930.png">

**AFTER**

<img width="1164" alt="Screenshot 2023-03-30 at 17 14 36" src="https://user-images.githubusercontent.com/2523391/228902658-04975236-e727-4adc-99ac-70f6b9bff059.png">

2. The original code didn't generate isotopes for all adducts, only for the M+H I think. Not sure if this is by design or a bug? In the new code it generates all adduct-isotope combinations.

**BEFORE**

<img width="1023" alt="Screenshot 2023-03-30 at 15 46 03" src="https://user-images.githubusercontent.com/2523391/228903234-d9217b2a-fd6d-45ff-a27b-10033eb199e2.png">

**AFTER**

<img width="993" alt="Screenshot 2023-03-30 at 15 46 22" src="https://user-images.githubusercontent.com/2523391/228903261-f0be8bb3-7d4e-456f-a7af-a2a4a107e329.png">

This shouldn't affect our previous results as in the papers we only used monoisotope and M+H adduct, so it should be okay to leave the codes as they are now, since it's more realistic.

3. Unit tests are still broken in GitHub Action, which is annoying ...

**Comment by mcbrider5002** [comment]
Seems to work for me now @joewandy.
