### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by joewandy** [sdrogers/vimms#259]
@mcbrider5002 tried to run [simulated_justinbeer_generation.ipynb](https://github.com/glasgowcompbio/vimms/blob/master/examples/03.%20TopNEXt%20(McBride%20et%20al%202023)/simulated_justinbeer_generation.ipynb), but encountered this error:

```
Traceback (most recent call last):
  File "C:\Users\mcbrider5002\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\mcbrider5002\anaconda3\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\Experiment.py", line 305, in _run_case
    return case.run_controller(
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\Experiment.py", line 208, in run_controller
    env.run()
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\Environment.py", line 87, in run
    raise e
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\Environment.py", line 83, in run
    scan = self._one_step()
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\Environment.py", line 110, in _one_step
    scan = self.mass_spec.step(params=params)
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 396, in step
    new_scan = self._get_scan(self.time, params)
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 609, in _get_scan
    chems, chemical_peaks = self._get_chem_peaks(isolation_windows, scan_time,
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 672, in _get_chem_peaks
    chemical_peaks = self._get_chem_peaks_for_ms2(chems, self.chem_data_collector,
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 693, in _get_chem_peaks_for_ms2
    chemical_peaks = self._get_children_spectra(chems, isolated_chems,
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 735, in _get_children_spectra
    self._get_mz_peaks_child(chemical.children[i], query_rt,
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 852, in _get_mz_peaks_child
    ms1_intensity = self._get_intensity_ms1(chemical.parent, query_rt,
  File "C:\Users\mcbrider5002\anaconda3\lib\site-packages\vimms\MassSpec.py", line 873, in _get_intensity_ms1
    return intensity * chemical.chromatogram.get_relative_intensity(
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

**Comment by joewandy** [comment]
Found another error when trying to run the notebook above. It's at this cell ..

<img width="1358" alt="image" src="https://github.com/glasgowcompbio/vimms/assets/2523391/89d3f19d-f199-4f7b-ab9e-78d3e1f0caa9">


Error is:
```
Creating Chemicals...
Generating chemicals for /Users/joewandy/University of Glasgow/Vinny Davies - CLDS Metabolomics Project/Data/multibeers_urine_data/beers/fullscan/mzML/Beer_multibeers_1_fullscan1.mzML

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "[/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py)", line 125, in worker
    result = (True, func(*args, **kwds))
  File "[/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py)", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "[/Users/joewandy/Work/git/vimms/vimms/Experiment.py](https://file+.vscode-resource.vscode-cdn.net/Users/joewandy/Work/git/vimms/vimms/Experiment.py)", line 294, in _gen_chems
    cm = ChemicalMixtureFromMZML(fs, roi_params=rp, ms2_sampler=FixedMS2Sampler())
  File "[/Users/joewandy/Work/git/vimms/vimms/Chemicals.py](https://file+.vscode-resource.vscode-cdn.net/Users/joewandy/Work/git/vimms/vimms/Chemicals.py)", line 823, in __init__
    self.good_rois = self._extract_rois()
  File "[/Users/joewandy/Work/git/vimms/vimms/Chemicals.py](https://file+.vscode-resource.vscode-cdn.net/Users/joewandy/Work/git/vimms/vimms/Chemicals.py)", line 833, in _extract_rois
    good = make_roi(str(self.mzml_file_name), self.roi_params)
  File "[/Users/joewandy/Work/git/vimms/vimms/Roi.py](https://file+.vscode-resource.vscode-cdn.net/Users/joewandy/Work/git/vimms/vimms/Roi.py)", line 1157, in make_roi
    run = pymzml.run.Reader(input_file, MS1_Precision=5e-6,
  File "[/opt/anaconda3/envs/vimms/lib/python3.9/site-packages/pymzml/run.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/site-packages/pymzml/run.py)", line 116, in __init__
    self.info["encoding"] = self._determine_file_encoding(path_or_file)
  File "[/opt/anaconda3/envs/vimms/lib/python3.9/site-packages/pymzml/run.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/site-packages/pymzml/run.py)", line 263, in _determine_file_encoding
    return self._guess_encoding(sniffer)
  File "[/opt/anaconda3/envs/vimms/lib/python3.9/site-packages/pymzml/run.py](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/site-packages/pymzml/run.py)", line 239, in _guess_encoding
    match = regex_patterns.FILE_ENCODING_PATTERN.search(mzml_file.readline())
TimeoutError: [Errno 60] Operation timed out
"""

The above exception was the direct cause of the following exception:

TimeoutError                              Traceback (most recent call last)
Input In [17], in ()
      4 same_beer_exp = Experiment()
      5 same_beer_exp.add_cases(
      6     ExperimentCase(controller_type, multibeer_fullscans[:1] * repeat, params, name=name, pickle_env=True)
      7     for controller_type, name, params in cases
      8 )
----> 9 same_beer_exp.run_experiment(
     10     out_dir,
     11     min_rt=min_rt,
     12     max_rt=max_rt,
     13     ionisation_mode=ionisation_mode,
     14     scan_duration_dict=scan_duration_dict,
     15     overwrite_keyfile=False,
     16     point_noise_threshold=point_noise_threshold,
     17     num_workers=num_workers
     18 )

File [~/Work/git/vimms/vimms/Experiment.py:350](https://file+.vscode-resource.vscode-cdn.net/Users/joewandy/Work/git/vimms/examples/03.%20TopNEXt%20%28McBride%20et%20al%202023%29/~/Work/git/vimms/vimms/Experiment.py:350), in Experiment.run_experiment(self, out_dir, pbar, min_rt, max_rt, ionisation_mode, scan_duration_dict, point_noise_threshold, chem_noise_threshold, overwrite_keyfile, num_workers)
    348 pathlib.Path(out_dir).mkdir(parents=True, exist_ok=True)
    349 self.out_dir = out_dir
--> 350 chems = self.create_chems(
    351     out_dir, 
    352     ionisation_mode, 
    353     num_workers, 
    354     point_noise_threshold=point_noise_threshold,
    355     chem_noise_threshold=chem_noise_threshold
    356 )
    357 print()
    358 print(f"Running Experiment of {len(self.cases)} cases...")

File [~/Work/git/vimms/vimms/Experiment.py:331](https://file+.vscode-resource.vscode-cdn.net/Users/joewandy/Work/git/vimms/examples/03.%20TopNEXt%20%28McBride%20et%20al%202023%29/~/Work/git/vimms/vimms/Experiment.py:331), in Experiment.create_chems(self, out_dir, ionisation_mode, num_workers, point_noise_threshold, chem_noise_threshold)
    323 with multiprocessing.Pool(num_workers) as pool:
    324     zipped = zip(
    325         all_fullscans,
    326         itertools.repeat(ionisation_mode),
   (...)
    329         itertools.repeat(chem_noise_threshold)
    330     )
--> 331     pkl_names = pool.starmap(self._gen_chems, zipped)
    333 return {fs : pkl for fs, pkl in zip(all_fullscans, pkl_names)}

File [/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py:372](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py:372), in Pool.starmap(self, func, iterable, chunksize)
    366 def starmap(self, func, iterable, chunksize=None):
    367     '''
    368     Like `map()` method but the elements of the `iterable` are expected to
    369     be iterables as well and will be unpacked as arguments. Hence
    370     `func` and (a, b) becomes func(a, b).
    371     '''
--> 372     return self._map_async(func, iterable, starmapstar, chunksize).get()

File [/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py:771](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/vimms/lib/python3.9/multiprocessing/pool.py:771), in ApplyResult.get(self, timeout)
    769     return self._value
    770 else:
--> 771     raise self._value

TimeoutError: [Errno 60] Operation timed out
```

**Comment by mcbrider5002** [comment]
@joewandy I think I might've found the cause for my error. The function in the error message at https://github.com/glasgowcompbio/vimms/blob/f6ca8dce90763a11a813a95e1a7e2b095a5b3e40/vimms/MassSpecUtils.py#LL90C1-L91C20 can return `None` if it fails an RT bounds check. Also, the boundary condition for RT match at https://github.com/glasgowcompbio/vimms/blob/f6ca8dce90763a11a813a95e1a7e2b095a5b3e40/vimms/MassSpecUtils.py#LL73C1-L73C1 is exclusive. 

```python
@njit
def rt_match(min_rt: float64, max_rt: float64, query_rt: float64) -> float64:
    return min_rt < query_rt < max_rt
```

When I changed those to non-strict equalities, it seems it ran past the point that it crashed previously. When the chemicals are filtered at an earlier point, they are moved off the stack if they fail a non-strict RT check: https://github.com/glasgowcompbio/vimms/blob/f6ca8dce90763a11a813a95e1a7e2b095a5b3e40/vimms/Chemicals.py#LL422C8-L422C8 . So I'd guess just because that notebook runs so many calculations that it eventually manages to find a chemical where the query RT hits the same float value as a chemical's RT end and then the mismatched boundary conditions become a problem. (At the time of writing, the rest of the notebook is still running, but hopefully it succeeds.)

This doesn't help with your error though. I can't reproduce that one myself so I can't test it myself (sorry). I'd try removing the multiprocessing from the bit that generates the chemicals or changing my pymzml version and see if either of those fix anything.

**Comment by mcbrider5002** [comment]
New error on the second cell this time...
![image](https://github.com/glasgowcompbio/vimms/assets/25082420/3ca7887a-9e7b-49aa-9db7-219d952a4c7d)

I think the issue is the divide on line 109.
```python
@njit
def get_relative_mz_intensity_values(query_rt: float64,
                                     mz_arr: np.ndarray, rt_arr: np.ndarray,
                                     intensity_arr: np.ndarray,
                                     with_intensity: bool) -> float64:
    which_above = bisect_right(rt_arr, query_rt)
    which_below = which_above - 1
    rt_below = rt_arr[which_below]
    rt_above = rt_arr[which_above]
    distance = (query_rt - rt_below) / (rt_above - rt_below)

    value_below = mz_arr[which_below]
    value_above = mz_arr[which_above]
    rel_mz = value_below + (value_above - value_below) * distance

    rel_int = np.nan
    if with_intensity:
        value_below = intensity_arr[which_below]
        value_above = intensity_arr[which_above]
        rel_int = value_below + (value_above - value_below) * distance

    return rel_mz, rel_int
```

It could have zero if there were two consecutive identical values in rt_arr. I'll try returning early if it would be zero and see if that will fix it...

**Comment by mcbrider5002** [comment]
When turning off numba, the divide-by-zero error disappeared, but an out-of-bounds indexing error appeared instead. This error was due to the use of `bisect_right` (if the exact value you were searching was the last value in the array, then this would cause an error - the check I mentioned before checks it falls somewhere within the bounds of the array non-strictly). I've replaced it with `bisect_left` which doesn't have this problem.

With that fix the code without numba ran to completion. I think this is because it's a numpy division, so the value just became NaN and got filtered out at some point harmlessly. But numba seems to be stricter and throws an exception. What the code is doing is bisecting, taking the insertion point as the right endpoint point of an interval, and then looking to the left by one value for the left endpoint, and using the length of this interval for a division. With `bisect_right` you can have that two identical values are next to each other and generate a divide-by-zero, but `bisect_left` doesn't typically have this problem since you look to the left afterwards. (I'm not sure how the code worked with `bisect_right` to begin with - maybe numba has different indexing semantics somehow?) 

However, if the array is only populated with one unique value the insertion point will be index zero, and the value to the left -1, which will wrap around to the end of the array. Since the array has only one unique value, you'll end up in that case even with `bisect_left`. These objects are `Chemicals`, specifically `UnknownChemicals` built with the RoI builder, so this happens when they only appear in one scan. These _should_ be filtered out by the `RoiParams` passed to `ChemicalMixtureFromMZML` having a minimum value of 2, but it's possible for an RoI to have multiple points at the same RT if they lie within the m/z interval, and the checks for RoI length checked the total number of points they are in rather than the number of unique scans they appear in. Consequently, it was possible for an RoI appearing in only one scan to have multiple points and not be filtered out, causing this divide-by-zero. I've updated the `Roi` class with a method `get_num_unique_scans` to check its length in scans and updated the length checks to use it instead.

NB: The interpolation as it stands won't work with `Chemicals` of one scan afaik, which includes spike noise, because any interpolated point that doesn't lie between two scans containing points in the range for interpolation is just dropped.

You can see the changes here: https://github.com/glasgowcompbio/vimms/commit/3047695309fe21fde57225d2d4a47df786b5e47d

The issue on my end should be resolved now, but I don't know about the error the notebook was having when run on your machine @joewandy?

**Comment by joewandy** [comment]
fixed by ross
